### ISSUE TITLE
关于加入噪声的维度问题

### ISSUE THREAD

**Issue by akajinchen** [SeeGera/SeeGera#2]
想问下作者，为什么加入的噪声是三维的呢？

**Comment by akajinchen** [comment]
对代码中的k,j参数也不是很理解，恳请作者解答

**Comment by tdye24** [comment]
> 想问下作者，为什么加入的噪声是三维的呢？
以此为例：
node_noise_e = self.noise_dist.sample(torch.Size([num_nodes, self.K + self.J, [self.noise_dim]))](https://github.com/SeeGera/SeeGera/blob/ed5156119b1ed29859de69c3b729d2a00a2034b4/model.py#L99C9-L99C104)
第一维是节点个数，第二维是K+J，第三维是噪声维度

**Comment by akajinchen** [comment]
明白了 感谢
